### ISSUE TITLE
IgnoreConstant没提交

### ISSUE THREAD

**Issue by PengsongAndroid** [DevMeteor/AutoDD#1]
cn.devmeteor.autodd.constant.IgnoreConstant 这个文件没传

**Comment by DevMeteor** [comment]
这里存放的是要解锁屏幕的点击命令序列和发送QQ消息的对象QQ号或者QQ群号
![image](https://user-images.githubusercontent.com/25410231/84630698-e4291a00-af1e-11ea-8936-0795a8e0d6b7.png)
